package com.littlehow.job.manager.model.job;

import java.util.Date;

public class TaskManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.task_id
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.business_id
     *
     * @mbggenerated
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.task_type
     *
     * @mbggenerated
     */
    private Byte taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.expression
     *
     * @mbggenerated
     */
    private String expression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.callback_url
     *
     * @mbggenerated
     */
    private String callbackUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job..task_manager.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.task_id
     *
     * @return the value of job..task_manager.task_id
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.task_id
     *
     * @param taskId the value for job..task_manager.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.business_id
     *
     * @return the value of job..task_manager.business_id
     *
     * @mbggenerated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.business_id
     *
     * @param businessId the value for job..task_manager.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.task_type
     *
     * @return the value of job..task_manager.task_type
     *
     * @mbggenerated
     */
    public Byte getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.task_type
     *
     * @param taskType the value for job..task_manager.task_type
     *
     * @mbggenerated
     */
    public void setTaskType(Byte taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.expression
     *
     * @return the value of job..task_manager.expression
     *
     * @mbggenerated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.expression
     *
     * @param expression the value for job..task_manager.expression
     *
     * @mbggenerated
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.callback_url
     *
     * @return the value of job..task_manager.callback_url
     *
     * @mbggenerated
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.callback_url
     *
     * @param callbackUrl the value for job..task_manager.callback_url
     *
     * @mbggenerated
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.create_time
     *
     * @return the value of job..task_manager.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.create_time
     *
     * @param createTime the value for job..task_manager.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.update_time
     *
     * @return the value of job..task_manager.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.update_time
     *
     * @param updateTime the value for job..task_manager.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job..task_manager.deleted
     *
     * @return the value of job..task_manager.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job..task_manager.deleted
     *
     * @param deleted the value for job..task_manager.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}